name: sadiaassignmentproject
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
#  google_fonts: ^4.0.3
#  dartz: ^0.10.1
#  shimmer: ^2.0.0
#  connectivity_plus: ^4.0.1
#  intl:
#  flutter_screenutil: ^5.7.0
#  platform:

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  assets:
    - assets/graphics/
    - assets/graphics/light/
    - assets/graphics/light/icons/
    - assets/graphics/light/images/
    - assets/graphics/dark/
    - assets/graphics/dark/icons/
    - assets/graphics/app_icon/

